# Generated by Django 5.1.7 on 2025-03-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_password_user_password_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.FloatField(default=0, verbose_name='临时得分'),
        ),
    ]
