# Generated by Django 5.1.7 on 2025-03-20 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_user_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='团队名称')),
                ('description', models.TextField(verbose_name='描述')),
                ('score', models.FloatField(verbose_name='得分')),
                ('created_at', models.DateTimeField()),
                ('captain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captain_team', to='account.user')),
                ('users', models.ManyToManyField(related_name='member_teams', to='account.user')),
            ],
        ),
    ]
