# Generated by Django 5.1.7 on 2025-03-20 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_user_score'),
        ('challenge', '0014_remove_challenge_score'),
        ('training', '0008_alter_training_challenge_alter_training_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='比赛名称')),
                ('status', models.IntegerField(choices=[(0, '未开始'), (1, '进行中'), (2, '已结束'), (3, '已暂停')], default=0, verbose_name='比赛状态')),
                ('category', models.IntegerField(choices=[(0, 'CTF'), (1, 'AWD'), (2, 'ISW')], default=0, verbose_name='比赛类型')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('description', models.TextField(verbose_name='比赛介绍')),
                ('rules', models.TextField(verbose_name='规则')),
                ('is_team', models.BooleanField(default=False, verbose_name='是否是团队赛')),
                ('challenges', models.ManyToManyField(related_name='competitions', to='challenge.challenge', verbose_name='题目')),
                ('users', models.ManyToManyField(blank=True, related_name='competitions', to='account.user', verbose_name='个人赛选择')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionTraining',
            fields=[
                ('training_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='training.training')),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competition_trainings', to='competition.competition')),
            ],
            bases=('training.training',),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='团队名称')),
                ('description', models.TextField(verbose_name='描述')),
                ('score', models.FloatField(verbose_name='得分')),
                ('created_at', models.DateTimeField()),
                ('captain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captain_teams', to='account.user')),
                ('users', models.ManyToManyField(related_name='member_teams', to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionTrainingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_flag', models.CharField(max_length=255, verbose_name='用户提交的FLAG')),
                ('is_correct', models.BooleanField(default=False, verbose_name='提交的是否正确')),
                ('submitted_at', models.DateTimeField(verbose_name='提交时间')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='该题得分')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.competitiontraining')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.team')),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='competitions', to='competition.team', verbose_name='团队赛选择'),
        ),
    ]
