# Generated by Django 5.1.7 on 2025-03-20 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_remove_team_captain_remove_team_users'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitiontraininglog',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.team'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='competitions', to='team.team', verbose_name='团队赛选择'),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
