# Generated by Django 5.1.7 on 2025-03-21 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_alter_competitiontraininglog_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitiontraininglog',
            name='competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='competition.competition'),
        ),
    ]
