# Generated by Django 5.1.7 on 2025-03-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0005_competitiontraining_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitiontraininglog',
            name='score',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='该题得分'),
        ),
    ]
