# Generated by Django 5.1.7 on 2025-03-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='run_url',
            field=models.CharField(blank=True, max_length=300, verbose_name='启动文件具体位置'),
        ),
    ]
