# Generated by Django 5.1.7 on 2025-03-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_challenge_difficulty_alter_challenge_flag_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='添加日期'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='related_url',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='相关链接'),
        ),
    ]
