# Generated by Django 5.1.7 on 2025-03-18 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_alter_challenge_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='categories',
            new_name='category',
        ),
    ]
