# Generated by Django 5.1.7 on 2025-03-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0005_rename_categories_challenge_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='cpu_limit',
            field=models.IntegerField(blank=True, null=True, verbose_name='CPU核数'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='memory_limit',
            field=models.IntegerField(blank=True, null=True, verbose_name='分配内存'),
        ),
    ]
