# Generated by Django 5.1.7 on 2025-03-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0006_challenge_cpu_limit_challenge_memory_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='static_flag',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='静态FLAG'),
        ),
    ]
