# Generated by Django 5.1.7 on 2025-03-19 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0007_challenge_static_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='cpu_limit',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='memory_limit',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='static_flag',
        ),
    ]
