# Generated by Django 5.1.7 on 2025-03-19 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0008_remove_challenge_cpu_limit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='run_url',
            new_name='config_dir',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='flag_type',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='run_type',
        ),
    ]
