# Generated by Django 5.1.7 on 2025-03-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0009_rename_run_url_challenge_config_dir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='image_existed',
            field=models.BooleanField(default=False, verbose_name='镜像是否存在， 是否可以启动'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='config_dir',
            field=models.CharField(blank=True, max_length=300, verbose_name='启动文件具体位置 /var/challenges/ '),
        ),
    ]
