# Generated by Django 5.1.7 on 2025-03-20 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0010_challenge_image_existed_alter_challenge_config_dir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='config_dir',
            field=models.CharField(max_length=300, verbose_name='启动文件具体位置 /var/challenges/ '),
        ),
    ]
