# Generated by Django 5.1.7 on 2025-03-20 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0011_alter_challenge_config_dir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges', to='challenge.category', verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='challenges', to='challenge.tag', verbose_name='标签'),
        ),
    ]
