# Generated by Django 5.1.7 on 2025-03-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0012_alter_challenge_category_alter_challenge_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='score',
            field=models.FloatField(default=0, verbose_name='分数'),
        ),
    ]
