# Generated by Django 5.1.7 on 2025-03-20 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0013_challenge_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='score',
        ),
    ]
