# Generated by Django 5.1.7 on 2025-03-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0014_remove_challenge_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='is_dockerd',
            field=models.BooleanField(default=True, verbose_name='是否需要docker运行'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='config_dir',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='启动文件具体位置 /var/challenges/ '),
        ),
    ]
