# Generated by Django 5.1.7 on 2025-03-18 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_rename_password_user_password_hash'),
        ('challenge', '0003_challenge_difficulty_alter_challenge_flag_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '启动中'), (1, '运行中'), (2, '已停止'), (3, '错误')], default=0, verbose_name='题目状态')),
                ('content', models.CharField(blank=True, max_length=500, null=True, verbose_name='题目内容')),
                ('flag', models.CharField(blank=True, max_length=255, null=True, verbose_name='FLAG值')),
                ('pwnd', models.BooleanField(default=False, verbose_name='是否被攻破')),
                ('container_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='DOCKER容器id')),
                ('cpu_limit', models.IntegerField(blank=True, null=True, verbose_name='CPU核数')),
                ('memory_limit', models.IntegerField(blank=True, null=True, verbose_name='分配内存')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='启动时间')),
                ('stopped_at', models.DateTimeField(blank=True, null=True, verbose_name='停止时间安')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.challenge', verbose_name='题目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user', verbose_name='谁开启的题目')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_flag', models.CharField(max_length=255, verbose_name='用户提交的FLAG')),
                ('is_correct', models.BooleanField(default=False, verbose_name='提交的是否正确')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.training')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
    ]
