# Generated by Django 5.1.7 on 2025-03-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='stopped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='停止时间'),
        ),
    ]
