# Generated by Django 5.1.7 on 2025-03-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_alter_training_stopped_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='cpu_limit',
        ),
        migrations.RemoveField(
            model_name='training',
            name='memory_limit',
        ),
        migrations.AddField(
            model_name='training',
            name='default_duration',
            field=models.PositiveIntegerField(default=3600),
        ),
        migrations.AddField(
            model_name='training',
            name='extend_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='training',
            name='extend_duration',
            field=models.PositiveIntegerField(default=1800),
        ),
        migrations.AddField(
            model_name='training',
            name='max_extend_count',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
