# Generated by Django 5.1.7 on 2025-03-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_remove_training_cpu_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='cpu_limit',
            field=models.IntegerField(blank=True, null=True, verbose_name='CPU核数'),
        ),
        migrations.AddField(
            model_name='training',
            name='memory_limit',
            field=models.IntegerField(blank=True, null=True, verbose_name='分配内存'),
        ),
    ]
