# Generated by Django 5.1.7 on 2025-03-20 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_training_disk_limit_alter_training_cpu_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='created_at',
            field=models.DateTimeField(verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='training',
            name='started_at',
            field=models.DateTimeField(verbose_name='启动时间'),
        ),
        migrations.AlterField(
            model_name='traininglog',
            name='submitted_at',
            field=models.DateTimeField(verbose_name='提交时间'),
        ),
    ]
