# Generated by Django 5.1.7 on 2025-03-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_alter_training_created_at_alter_training_started_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='training',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='启动时间'),
        ),
    ]
